wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.19
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.5.6
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 2
      4: 3.5.6
      5: 0.10.19
      8:
      - 1
